name: flex_workout_logger
description: "Workout app by Matt Dunn and Mitch Joram"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  intl: ^0.18.1
  realm: ^1.9.0
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.2.2
  validators: ^3.0.0
  xml: ^6.3.0
  path_drawing: ^1.0.1
  cupertino_icons: ^1.0.6
  flutter_slidable: ^3.0.1
  custom_sliding_segmented_control: ^1.8.1
  flow_builder: ^0.0.10
  dotted_border: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/engagement.100x100.png
    - assets/icons/equipment.100x100.png
    - assets/icons/exercise.primary.100x100.png
    - assets/icons/exercise.blue.100x100.png
    - assets/icons/movement.100x100.png
    - assets/icons/muscle.100x100.png
    - assets/icons/type.100x100.png

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/app-icon.png"
  image_path_android: "assets/images/app-icon.png"
